name: Run Data Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  RUN_TYPE: garmin
  ATHLETE: Хэнк
  TITLE: Хэнк ебланит
  MIN_GRID_DISTANCE: 3
  TITLE_GRID: Over 3km Runs
  BUILD_GH_PAGES: true

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    outputs:
      SAVE_DATA_IN_GITHUB_CACHE: false
      DATA_CACHE_PREFIX: 'track_data'
      BUILD_GH_PAGES: ${{ steps.set_output.outputs.BUILD_GH_PAGES }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator from GPX files
        run: |
          export PYTHONPATH=.
          python run_page/gpx_sync.py --gpx-dir activities

      - name: Push new runs
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add src/static/
          git add run_page/
          git add .
          git commit -m 'update static files from gpx' || echo 'nothing to commit'
          git push || echo 'nothing to push'

      - name: Set Output
        id: set_output
        run: |
          echo "BUILD_GH_PAGES=true" >> "$GITHUB_OUTPUT"

  publish_github_pages:
    if: needs.sync.result == 'success'
    name: Build and publish Github Pages
    uses: ./.github/workflows/gh-pages.yml
    with:
      save_data_in_github_cache: false
      data_cache_prefix: 'track_data'
    needs:
      - sync
